# Generated by Django 2.1.2 on 2020-10-10 14:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20201010_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 11, 14, 36, 14, 31726, tzinfo=utc), verbose_name='date end'),
        ),
    ]
