# Generated by Django 2.1.2 on 2020-10-30 13:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20201010_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 31, 13, 50, 8, 636938, tzinfo=utc), verbose_name='date end'),
        ),
    ]
